language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"
before_install:
  - sudo apt-get install oracle-java8-installer
  - sudo apt-get install oracle-java8-set-default
  - java -version
  - unset JAVA_HOME
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script: py.test -v --waitlong --cov=infinispan
after_success: coveralls
